#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ENVision.Resource", IsApplication=true)]

namespace ENVision
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_passive_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button_style = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_passive_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_style = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_ok = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Menu = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int b_cancel = 2131034123;
			
			// aapt resource value: 0x7f050013
			public const int b_date = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int b_end = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int b_finish = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int b_menu = 2131034112;
			
			// aapt resource value: 0x7f05001e
			public const int b_minus = 2131034142;
			
			// aapt resource value: 0x7f050005
			public const int b_more = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int b_next = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int b_picture = 2131034116;
			
			// aapt resource value: 0x7f050020
			public const int b_plus = 2131034144;
			
			// aapt resource value: 0x7f05000c
			public const int b_save = 2131034124;
			
			// aapt resource value: 0x7f05001d
			public const int b_share = 2131034141;
			
			// aapt resource value: 0x7f050016
			public const int b_start = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int b_weekly = 2131034132;
			
			// aapt resource value: 0x7f050008
			public const int btnMove = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int btn_login = 2131034127;
			
			// aapt resource value: 0x7f050012
			public const int et0 = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int et1 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int et2 = 2131034129;
			
			// aapt resource value: 0x7f050003
			public const int et_name = 2131034115;
			
			// aapt resource value: 0x7f05000e
			public const int et_phone = 2131034126;
			
			// aapt resource value: 0x7f05000a
			public const int et_value = 2131034122;
			
			// aapt resource value: 0x7f050021
			public const int fl_chart = 2131034145;
			
			// aapt resource value: 0x7f050007
			public const int iv_picture = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int ll_report = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int lv_products = 2131034113;
			
			// aapt resource value: 0x7f050022
			public const int menu_new_product = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int menu_report = 2131034152;
			
			// aapt resource value: 0x7f050026
			public const int menu_sell = 2131034150;
			
			// aapt resource value: 0x7f050023
			public const int menu_set_costs = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int menu_set_prices = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int menu_set_stock = 2131034149;
			
			// aapt resource value: 0x7f050029
			public const int menu_signout = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int menu_wreport = 2131034151;
			
			// aapt resource value: 0x7f05000d
			public const int pbHeaderProgress = 2131034125;
			
			// aapt resource value: 0x7f050018
			public const int tv_earned = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int tv_growth = 2131034139;
			
			// aapt resource value: 0x7f050009
			public const int tv_label = 2131034121;
			
			// aapt resource value: 0x7f05001c
			public const int tv_loss = 2131034140;
			
			// aapt resource value: 0x7f05001a
			public const int tv_profit = 2131034138;
			
			// aapt resource value: 0x7f05001f
			public const int tv_qty = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int tv_spent = 2131034137;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddCostActivity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddPriceActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddProductActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddStockActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int CompleteActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int EditScreenTVGeneric = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoadingActivity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int LoginActivity = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int LVImageEditLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int LVPOSLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int LVTextButtonLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int LVTextEditLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int LVTextTextLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int POSActivity = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int ReportActivity = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int SelectStockPOSActivity = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int WeeklyReportActivity = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
